# Build configuration file for Circle CI
version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      - run:
          name: Install Build Tools
          command: echo y | sdkmanager "build-tools;26.0.2"
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
      #- run:
      #    name: Run Android Lint
      #    command: ./gradlew lintStagingDebug -PpreDexEnable=false -PdisablePreDex --console=plain
      #- run:
      #    name: Run PMD
      #    command: ./gradlew pmd -PpreDexEnable=false -PdisablePreDex --console=plain
      #- run:
      #    name: Run Checkstyle
      #    command: ./gradlew checkstyle -PpreDexEnable=false -PdisablePreDex --console=plain
      #- run:
      #    name: Run Findbugs
      #    command: ./gradlew findbugs -PpreDexEnable=false -PdisablePreDex --console=plain
      - run:
          name: Accept Licenses
          command: yes | sdkmanager --licenses && sdkmanager --update
      - run:
          name: Run Tests
          command: ./gradlew connectedAndroidTest -PpreDexEnable=false -PdisablePreDex --console=plain
          #command: ./gradlew testStagingDebug -PpreDexEnable=false -PdisablePreDex --console=plain
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/outputs
          destination: outputs
      - store_test_results:
          path: app/build/test-results
      - deploy:
          name: Labs
          command: |
            if [ "${CIRCLE_TAG}" != "" ]; then
              ./gradlew clean assembleStagingDebug -PpreDexEnable=false -PdisablePreDex --console=plain
              sudo apt-get install build-essential
              sudo apt-get install rubygems
              sudo apt-get install ruby-dev
              sudo gem install bundler
              ./config/deploy.sh
            fi
deployment:
  labs:
    tag: /labs\/.*/

experimental:
  # this will enable chat notifications only for certain branches
  notify:
    branches:
      only:
        - labs
        - dev
